### ISSUE TITLE
Use palm for camera motion

### ISSUE THREAD

**Issue by kaseyc** [rhansby/leap-gamepad#1]
Currently, we use the stabilized tip position of the index finger to control camera motion. This works well except for trigger pulls cause the camera to dip. Should we consider switching to using the stabilized palm position instead?

@ipetkov @rhansby

**Comment by ipetkov** [comment]
Huh, I wonder why we didn't use palm position originally... I think that using the palm would make more sense actually.

**Comment by kaseyc** [comment]
Fixed.
